# Generated by Django 3.2 on 2024-10-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_carimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
