# Generated by Django 5.1.1 on 2024-10-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_delete_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='car',
            name='car_location',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='climate_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='cooled_seats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='dvd_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.CharField(blank=True, choices=[('1000cc', '1000cc'), ('1500cc', '1500cc'), ('2000cc', '2000cc')], default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='front_wheel_drive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.CharField(choices=[('100-150', '100-150'), ('150-200', '150-200'), ('200-250', '200-250')], default='100-150', max_length=25),
        ),
        migrations.AddField(
            model_name='car',
            name='is_insured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='keyless_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='leather_seats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='listing_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='navigation_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='parking_sensors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='premium_sound_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='rear_view_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='regional_spec',
            field=models.CharField(choices=[('GCC Specs', 'GCC Specs')], default='GCC Specs', max_length=25),
        ),
        migrations.AddField(
            model_name='car',
            name='seating_capacity',
            field=models.CharField(blank=True, choices=[('2', '2'), ('4', '4'), ('5', '5'), ('7', '7')], default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='steering_side',
            field=models.CharField(choices=[('Left Hand', 'Left Hand'), ('Right Hand', 'Right Hand')], default='Left Hand', max_length=25),
        ),
        migrations.AddField(
            model_name='car',
            name='tour_url',
            field=models.URLField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='trim',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_city',
            field=models.CharField(choices=[('Abu Dhabi', 'Abu Dhabi'), ('Dubai', 'Dubai'), ('Sharjah', 'Sharjah')], default='Abu Dhabi', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_color',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='car/car_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_version',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='expected_selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('lpg', 'LPG'), ('cng', 'CNG'), ('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=25),
        ),
        migrations.AlterField(
            model_name='car',
            name='kilometer_driven',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='make_month',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='make_year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
