# Generated by Django 5.1.1 on 2024-10-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0019_remove_car_id_car_body_type_car_car_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('listing_title',)},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_owner',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_owner_name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_photo',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_post_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_status',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_title',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_version',
        ),
        migrations.RemoveField(
            model_name='car',
            name='insurance_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='make_month',
        ),
        migrations.RemoveField(
            model_name='car',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='registration_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vehicle_type',
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.CharField(blank=True, choices=[('1000cc', '1000cc'), ('1500cc', '1500cc'), ('2000cc', '2000cc')], default='1500cc', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='make_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='car',
            name='seating_capacity',
            field=models.CharField(blank=True, choices=[('2', '2'), ('4', '4'), ('5', '5'), ('7', '7')], default='5', max_length=25, null=True),
        ),
    ]
