# Generated by Django 5.1.1 on 2024-10-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0023_car_vehicle_type_alter_carimage_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='car',
            name='regional_spec',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='car',
            name='seating_capacity',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='steering_side',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(default='', max_length=25),
        ),
    ]
