# Generated by Django 5.1.1 on 2024-10-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0024_alter_car_car_city_alter_car_engine_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
