# Generated by Django 5.1.1 on 2024-10-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0026_alter_car_id_alter_car_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='All cities', max_length=100)),
                ('code', models.CharField(default='All codes', max_length=100)),
                ('digits', models.CharField(default='Any digits', max_length=100)),
                ('contains', models.CharField(blank=True, max_length=100, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('starts_with', models.CharField(blank=True, max_length=100, null=True)),
                ('ends_with', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_format', models.CharField(blank=True, default='Any format', max_length=100, null=True)),
            ],
        ),
    ]
