# Generated by Django 5.1.1 on 2024-10-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0027_licenseplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseplate',
            name='contains',
        ),
        migrations.RemoveField(
            model_name='licenseplate',
            name='ends_with',
        ),
        migrations.RemoveField(
            model_name='licenseplate',
            name='starts_with',
        ),
    ]
