# Generated by Django 5.1.4 on 2025-01-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0028_remove_licenseplate_contains_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make_year',
            field=models.IntegerField(default=2025),
        ),
    ]
