# Generated by Django 5.1.4 on 2025-01-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0030_rename_max_price_licenseplate_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseplate',
            name='number',
            field=models.CharField(blank=True, default='Any number', max_length=100, null=True),
        ),
    ]
